// Arrays of post types and topics
const postTypes = [
  // Core engagement types
  "motivation",
  "intellect provocation",
  "emotion provocation",
  "throwback",
  "wisdom/education",
  "tips/advice",
  "inspiration",
  "story",
  "challenge",
  "q&a",
  "poll",
  "quiz",
  "question",
  "news/updates",
  
  // Expanded content formats
  "tutorial/step-by-step",
  "behind-the-scenes",
  "day-in-the-life",
  "product/service showcase",
  "AI-generated content",
  "customer testimonial",
  "case study",
  "infographic",
  "meme/humor",
  "interactive content",
  "live video",
  "AMA (Ask Me Anything)",
  "rant/opinion piece",
  "predictions/forecasts",
  
  // Specialized categories
  "book/movie/media recommendation",
  "resource roundup",
  "before-and-after",
  "myth-busting",
  "industry insights",
  "trend analysis",
  "historical facts",
  "scientific discoveries",
  "tech explainers",
  "cultural commentary",
  
  // Engagement boosters
  "fill-in-the-blank",
  "this-or-that",
  "caption contest",
  "tag a friend",
  "share your experience",
  "guess what/who",
  "would you rather",
  "spot the difference",
  
  // Personal growth
  "journal prompt",
  "self-reflection",
  "mindfulness exercise",
  "gratitude practice",
  "affirmation",
  "habits/routines",
  
  // Business specific
  "team introduction",
  "company values",
  "job opening",
  "event announcement",
  "milestone celebration",
  "award/achievement",
  "partnership announcement",
  "product launch",
  
  // Seasonal/holiday
  "holiday greeting",
  "seasonal tips",
  "year-in-review",
  "new year resolutions",
  "back-to-school",
  "summer/winter preparation",
  
  // Community building
  "meet-the-follower",
  "community spotlight",
  "user appreciation",
  "collaboration opportunity",
  "crowdsourcing ideas",
  
  // Controversial/discussion
  "hot take",
  "debate topic",
  "unpopular opinion",
  "ethical dilemma",
  
  // Visual content
  "photo diary",
  "carousel post",
  "timelapse",
  "animation/gif",
  "cinematic video",
  
  // Niche-specific
  "fitness challenge",
  "recipe share",
  "travel guide",
  "fashion lookbook",
  "art process",
  "coding tutorial",
  "financial tip",
  "parenting hack",
  
  // Meta posts
  "platform experiment",
  "algorithm test",
  "content feedback request",
  "lessons learned",
  "failure story",
  
  // Future-oriented
  "emerging technology",
  "future predictions",
  "next big thing",
  "career opportunities",
  
  // Nostalgia
  "decade comparison",
  "childhood memories",
  "vintage throwback",
  "how times have changed"
];

const topics = [
  // EMOTIONS & PSYCHOLOGY
  "emotions",
  "happiness",
  "sadness",
  "love",
  "hate",
  "arrogance",
  "psychology",
  "anger",
  "jealousy",
  "empathy",
  "compassion",
  "gratitude",
  "nostalgia",
  "anxiety",
  "depression",
  "emotional intelligence",
  "self-esteem",
  "confidence",
  "vulnerability",
  "forgiveness",

  // PHILOSOPHY & THEORY
  "ontology",
  "epistemology",
  "parrenialism",
  "ethics",
  "free will",
  "existentialism",
  "stoicism",
  "nihilism",
  "absurdism",
  "humanism",
  "rationalism",
  "empiricism",
  "pragmatism",
  "utilitarianism",
  "determinism",
  "dualism",
  "materialism",
  "idealism",
  "phenomenology",
  "hermeneutics",

  // SOCIETY & CULTURE
  "sociology",
  "the law",
  "the government",
  "bureaucracy",
  "pop figures",
  "brands",
  "social norms",
  "cultural trends",
  "generational differences",
  "subcultures",
  "counterculture",
  "urban life",
  "rural life",
  "gentrification",
  "globalisation",
  "cultural appropriation",
  "tradition",
  "modernity",
  "social justice",
  "identity politics",

  // FINANCE & ECONOMY
  "the economy",
  "money",
  "banking",
  "entrepreneurship",
  "investing",
  "cryptocurrency",
  "stock market",
  "real estate",
  "property letting",
  "taxation",
  "wealth inequality",
  "consumerism",
  "financial independence",
  "retirement planning",
  "side hustles",
  "freelancing",
  "corporate life",
  "unions",
  "minimum wage",
  "economic systems",

  // RELIGION & SPIRITUALITY
  "the bible",
  "religion",
  "idolatry",
  "esoterica",
  "spirituality",
  "meditation",
  "prayer",
  "atheism",
  "agnosticism",
  "new age",
  "occult",
  "mythology",
  "afterlife",
  "karma",
  "reincarnation",
  "divination",
  "rituals",
  "sacred texts",
  "faith healing",
  "religious art",

  // TECHNOLOGY
  "antiquated technology",
  "modern technology",
  "future technology",
  "ai",
  "robotics",
  "virtual reality",
  "augmented reality",
  "blockchain",
  "nanotechnology",
  "biotechnology",
  "quantum computing",
  "3D printing",
  "drones",
  "self-driving cars",
  "smart homes",
  "wearable tech",
  "cybersecurity",
  "data privacy",
  "space technology",
  "transhumanism",

  // LIFESTYLE
  "clothes",
  "shops/shopping",
  "travel",
  "housekeeping",
  "minimalism",
  "luxury living",
  "DIY culture",
  "home decor",
  "gardening",
  "sustainability",
  "zero waste",
  "slow living",
  "tiny homes",
  "coffee culture",
  "tea culture",
  "wine tasting",
  "craft beer",
  "mixology",

  // HEALTH & WELLNESS
  "healthy food",
  "unhealthy food",
  "alcohol",
  "drugs",
  "mental health day",
  "physical health day",
  "hygiene",
  "fitness",
  "yoga",
  "pilates",
  "crossfit",
  "veganism",
  "keto diet",
  "intermittent fasting",
  "sleep hygiene",
  "gut health",
  "mental resilience",
  "therapy",
  "self-care",
  "aging gracefully",

  // ARTS & CREATIVITY
  "art",
  "design",
  "beauty/aesthetics",
  "books",
  "music",
  "film",
  "theater",
  "dance",
  "photography",
  "creative writing",
  "poetry",
  "graffiti",
  "street art",
  "digital art",
  "crafts",
  "pottery",
  "woodworking",
  "fashion design",
  "architecture",
  "interior design",

  // SCIENCE & MATH
  "math",
  "physics",
  "chemistry",
  "biology",
  "astronomy",
  "geology",
  "meteorology",
  "neuroscience",
  "genetics",
  "paleontology",
  "archeology",
  "anthropology",
  "linguistics",
  "statistics",
  "probability",
  "game theory",
  "chaos theory",
  "complexity theory",
  "systems theory",
  "scientific method",

  // WORK & PROFESSIONAL
  "work",
  "code",
  "professionalism",
  "marketing",
  "efficiency",
  "organisation",
  "competence",
  "intelligence",
  "perseverance",
  "conviction",
  "success",
  "failure",
  "leadership",
  "teamwork",
  "networking",
  "public speaking",
  "time management",
  "productivity",
  "remote work",
  "corporate culture",

  // NATURE & ENVIRONMENT
  "wildlife",
  "pets",
  "survival",
  "climate change",
  "conservation",
  "national parks",
  "ocean life",
  "birdwatching",
  "botany",
  "permaculture",
  "organic farming",
  "renewable energy",
  "pollution",
  "sustainable living",
  "natural disasters",
  "geography",
  "ecotourism",
  "animal rights",
  "marine biology",
  "forest ecosystems",

  // HISTORY & LANGUAGE
  "the past",
  "greek/latin/hebrew",
  "ancient history",
  "medieval history",
  "modern history",
  "military history",
  "art history",
  "language learning",
  "etymology",
  "dialects",
  "sign language",
  "hieroglyphs",
  "historical fiction",
  "oral traditions",
  "folklore",
  "myths and legends",
  "archival research",
  "historical reenactment",
  "museum studies",
  "preservation",

  // FUTURE & SPECULATION
  "the future",
  "the coming apocalypse",
  "futurology",
  "space colonization",
  "post-scarcity",
  "singularity",
  "dystopian futures",
  "utopian futures",
  "climate futures",
  "future of work",
  "future of education",
  "future of transportation",
  "future of medicine",
  "generational forecasting",
  "longtermism",
  "existential risks",
  "speculative fiction",
  "alternative timelines",
  "parallel universes",
  "cryonics",

  // RELATIONSHIPS & FAMILY
  "parenthood",
  "childhood",
  "romance",
  "flirtation",
  "dating",
  "marriage",
  "divorce",
  "friendship",
  "sibling rivalry",
  "family traditions",
  "parenting styles",
  "adoption",
  "foster care",
  "long-distance relationships",
  "toxic relationships",
  "healthy boundaries",
  "emotional labor",
  "codependency",
  "platonic love",
  "intergenerational relationships",

  // LEISURE & HOBBIES
  "humor",
  "comedy",
  "games",
  "board games",
  "video games",
  "role-playing games",
  "puzzles",
  "magic tricks",
  "collecting",
  "cosplay",
  "LARPing",
  "birdwatching",
  "astrophotography",
  "model building",
  "scrapbooking",
  "genealogy",
  "home brewing",
  "baking",
  "mixology",
  "urban exploration",

  // TRANSPORTATION
  "cars",
  "motorcycles",
  "bicycles",
  "public transit",
  "aviation",
  "sailing",
  "trainspotting",
  "vintage vehicles",
  "electric vehicles",
  "hyperloop",
  "flying cars",
  "space tourism",
  "cruise ships",
  "road trips",
  "hitchhiking",
  "backpacking",
  "overlanding",
  "RV living",
  "hot air balloons",
  "submarines",

  // CONTROVERSIAL TOPICS
  "criminality",
  "death",
  "indulgence",
  "taboos",
  "conspiracy theories",
  "censorship",
  "propaganda",
  "fake news",
  "deepfakes",
  "surveillance",
  "whistleblowing",
  "hacking",
  "bioethics",
  "eugenics",
  "transhuman ethics",
  "right to die",
  "gun control",
  "abortion debate",
  "drug legalisation",
  "cancel culture",

  // REGIONAL TOPICS
  "scotland",
  "the uk",
  "european union",
  "north america",
  "south america",
  "africa",
  "asia",
  "middle east",
  "australia",
  "the arctic",
  "the antarctic",
  "island nations",
  "landlocked countries",
  "microstates",
  "city-states",
  "autonomous regions",
  "indigenous lands",
  "diaspora communities",
  "border disputes",
  "immigration policies",

  // TIME CONCEPTS
  "time",
  "punctuality",
  "time zones",
  "daylight saving",
  "calendar systems",
  "astrological ages",
  "biological clocks",
  "time perception",
  "time travel",
  "temporal paradoxes",
  "seasonal affects",
  "anniversaries",
  "milestones",
  "deadlines",
  "procrastination",
  "momentum",
  "impermanence",
  "eternity",
  "the present moment",
  "time capsules"
];
