// Arrays of post types and topics
const postTypes = [
  "motivation",
  "cognitive provocation",
  "emotional provocation",
  "throwback",
  "wisdom/education",
  "tips/advice",
  "inspiration",
  "story",
  "challenge",
  "q&a",
  "poll",
  "quiz",
  "question",
  "news/updates"
];

const topics = [
  "the latest “news”",
  "emotions",
  "happiness",
  "sadness",
  "arrogance",
  "love",
  "hate",
  "the economy",
  "money",
  "psychology",
  "sociology",
  "ontology",
  "epistemology",
  "parrenialism",
  "the law",
  "the government",
  "banking",
  "scotland",
  "the uk",
  "the bible",
  "religion",
  "humor",
  "esoterica",
  "survival",
  "greek/latin/hebrew",
  "antiquated technology",
  "modern technology",
  "future technology",
  "clothes",
  "bureaucracy",
  "alcohol",
  "drugs",
  "childhood",
  "wildlife",
  "pets",
  "beauty/aesthetics",
  "ethics",
  "books",
  "pop figures",
  "healthy food",
  "unhealthy food",
  "coffee",
  "professionalism",
  "parenthood",
  "the past",
  "the future",
  "ai",
  "time",
  "art",
  "design",
  "math",
  "code",
  "work",
  "entrepreneurship",
  "brands",
  "combat",
  "death",
  "shops/shopping",
  "the coming apocalypse",
  "security",
  "mental health day",
  "physical health day",
  "privacy",
  "comedy",
  "travel",
  "energy",
  "leadership",
  "teamwork",
  "indulgence",
  "marketing",
  "property letting",
  "housekeeping",
  "efficiency",
  "organisation",
  "criminality",
  "competence",
  "intelligence",
  "perseverance",
  "conviction",
  "romance",
  "flirtation",
  "success",
  "failure",
  "cars",
  "free will",
  "idolatry",
  "hygiene"
];
